name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -XPOST 'https://discord.com/api/webhooks/914810610221457438/GjiHGw4D7W6edTt81toar3mfFqNG3xzILboAhW1OPtgBdlQAL659_31UVm_WmnJUSSZ_' -H 'Content-Type: application/json' -d '{ "content": "Bonjour" }'